#!/bin/bash

# g++ -DYAKL_DEBUG -O0 -g -I/usr/include/hdf5/serial -std=c++17 -I .. -I ~/YAKL/src ~/YAKL/src/YAKL.cpp test.cpp -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5

# nvcc -O0 -g -DYAKL_DEBUG -DYAKL_ARCH_CUDA -arch=sm_61 --extended-lambda --expt-relaxed-constexpr -std=c++17 -x cu -I .. -I/usr/include/hdf5/serial -I ~/YAKL/src ~/YAKL/src/YAKL.cpp test.cpp -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5

nvcc -O3 -res-usage --use_fast_math -DYAKL_ARCH_CUDA -arch=sm_61 --extended-lambda --expt-relaxed-constexpr -std=c++17 -x cu -I .. -I/usr/include/hdf5/serial -I ~/YAKL/src ~/YAKL/src/YAKL.cpp test.cpp -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5
