name: linux

on:
  push:
    branches:
      - main
      - github*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 4
  MAKEFLAGS: "--jobs=4"

jobs:
  serial:
    name: ubuntu-24.04-serial
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7
    - name: dependencies
      run: |
        g++ -v
        cmake --version
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends \
            libopenmpi-dev \
            openmpi-bin
        git clone --branch 5.1.0 https://github.com/kokkos/kokkos.git
        git clone https://github.com/mrnorman/YAKL.git
        wget https://github.com/HDFGroup/hdf5/releases/download/2.1.1/hdf5-2.1.1.tar.gz
        tar xf hdf5-2.1.1.tar.gz
        cd hdf5-2.1.1/
        mkdir build
        cd build
        cmake -D HDF5_ENABLE_PARALLEL=ON -D CMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/hdf5/ ..
        make install
    - name: ponni
      run: |
        cd unit/build
        export KOKKOS_HOME=${GITHUB_WORKSPACE}/kokkos/
        export YAKL_HOME=${GITHUB_WORKSPACE}/YAKL/
        export HDF5_DIR=${GITHUB_WORKSPACE}/hdf5/
        cmake ..
        make
    - name: test
      run: |
        cd unit/build
        ./keras_resnet/keras_resnet ../keras_resnet/keras_resnet_data.h5
        ./keras_sequential/keras_sequential ../keras_sequential/keras_sequential_data.h5
        ./pytorch_resnet/pytorch_resnet ../pytorch_resnet/pytorch_resnet_data.h5 
        ./performance_benchmark/performance_benchmark
